name: Deploy Lambda (ZIP)
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      FUNCTION_NAME: nj-datamap
      AWS_REGION: eu-west-3
      NODE_VERSION: '20'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Package Lambda
        run: |
          zip -rq function.zip . \
            -x ".git/*" ".github/*" "node_modules/.cache/*" "**/*.test.*" "**/__tests__/**"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::838267895078:role/GitHubActionsDeployRole

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://function.zip \
            --publish
